// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3iPVa9Yvb0maobZ1QOGzcyyWbfC1MG-k',
    appId: '1:358048828340:web:7e5172bfe949fb228980e1',
    messagingSenderId: '358048828340',
    projectId: 'chatapp-fcd22',
    authDomain: 'chatapp-fcd22.firebaseapp.com',
    storageBucket: 'chatapp-fcd22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0N72nezjoRl6EtYtgAk-Rn-dYnpIJ7k',
    appId: '1:358048828340:android:f03f60b57364c7008980e1',
    messagingSenderId: '358048828340',
    projectId: 'chatapp-fcd22',
    storageBucket: 'chatapp-fcd22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFAf-Vc5w9KnZyrP_ZU1mF0_s0fB8RFo',
    appId: '1:358048828340:ios:1e0a9f06b5ea758f8980e1',
    messagingSenderId: '358048828340',
    projectId: 'chatapp-fcd22',
    storageBucket: 'chatapp-fcd22.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );
}
